// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtoQQcgPq7c5_m8HL7QqlbALCptExmNHA',
    appId: '1:903896789118:web:a1f49f923550ac1a5f682f',
    messagingSenderId: '903896789118',
    projectId: 'aniruddh-project-2',
    authDomain: 'aniruddh-project-2.firebaseapp.com',
    storageBucket: 'aniruddh-project-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnuruNGgZfrxrBto5pfBV3o6VByUN0A_Y',
    appId: '1:903896789118:android:9b07ad8914dd5b6a5f682f',
    messagingSenderId: '903896789118',
    projectId: 'aniruddh-project-2',
    storageBucket: 'aniruddh-project-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvEYOomOVNtnpQpjo418YJuOQNWCMxv0o',
    appId: '1:903896789118:ios:6d12703d1a109ad85f682f',
    messagingSenderId: '903896789118',
    projectId: 'aniruddh-project-2',
    storageBucket: 'aniruddh-project-2.appspot.com',
    iosClientId: '903896789118-01gtj7fnhrkp46u31klvbsps7ko7su4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWithFcc',
  );
}
